### ISSUE TITLE
Instructions to run the app

### ISSUE THREAD

**Issue by Shahrukh-Zindani** [joshwcomeau/fakebook#1]
@joshwcomeau Hey I would appreciate if you can the instructions to have this running.
It looks like it was made using create react app. 
I cloned the project.
`cd fakebook`
`npm install`
`npm start`
It displays an empty page.
This sounds like a fun project and if I can get it running, I would love to contributing to it.

**Comment by joshwcomeau** [comment]
Hey there!

So yeah, this was one of those projects I thought would be neat, but then life got in the way (started a new job), and eventually lost interest in completing it.

If you wanted to contribute to it, that'd be awesome! Happy to add you as a contributor :)

As for running it, your set of commands looks right to me. When running it locally I did indeed see a white page, but only for the ~20 seconds while Webpack built. Afterwards I saw the Facebook header, and the word "hello".

The homepage is blank because I was starting on the profile page. The way this works is I have stubs for various data sources; you can find the user ones in src/stubs/profiles.js. The stubs use Faker to randomly generate data, but you still have to specify a root user.

The only user right now is one I added based on myself: `joshwcomeau`. So, if you go to http://localhost:3000/joshwcomeau, you _should_ see:

<img width="999" alt="screen shot 2017-04-01 at 5 52 59 pm" src="https://cloud.githubusercontent.com/assets/6692932/24582730/180cccb0-1704-11e7-99f6-c56207f6b059.png">

Let me know if you're able to get this far. If not, do you see any errors when building or running?

**Comment by Shahrukh-Zindani** [comment]
@joshwcomeau Yeah man this page looks beautiful, I would like to do some digging into this project and build this to something even better if I get hooked.
I tried running it again and waiting quite a bit.
This is what I see.
<img width="1286" alt="screen shot 2017-04-01 at 5 03 23 pm" src="https://cloud.githubusercontent.com/assets/14262127/24582804/39af682a-16fd-11e7-92cc-6a8a9c05fd05.png">
It compiles fine with a few minor warnings. Appreciate your help man.

**Comment by joshwcomeau** [comment]
Ah-ha; So, the issue is that I built this with an alpha version of React Router v4, and the API has since changed with the final release.

Updating now, and making a few other small tweaks (switching to Yarn, for example). Will push an update soon :)

**Comment by joshwcomeau** [comment]
Ok! I just pushed an update, it should work now. You'll need to reset from origin, since I did do some rebasing on master (my bad!)

Lemme know if the issue remains unresolved, or if you run into any other hurdles! I think this project could indeed be a pretty neat resource :)

**Comment by Shahrukh-Zindani** [comment]
I was able to get the app running. I fiddle with the code in my free time and will try to make progress on it. It could turn into an amazingly helpful resource.
